from sqlalchemy import Column, ForeignKey, Integer, String, Numeric
from sqlalchemy.orm import relationship

from database import Base

class DimSymbol(Base):
    __tablename__ = "dim_symbol"

    symbol_id = Column(Integer, primary_key=True, index=True)
    symbol = Column(String, index=True)
    symbol_name = Column(String)
    cik = Column(String)
    isin = Column(String)
    cusip = Column(String)
    ein_employer_id = Column(String)
    lei = Column(String)
    series_id = Column(String)
    item_type = Column(String)
    sector = Column(String)
    industry = Column(String)
    sic_code = Column(String)
    sic_name = Column(String)

    balance_sheets = relationship("BalanceSheet", back_populates="dim_symbol")

class BalanceSheet(Base):
    __tablename__ = "fact_balance_sheet"

    symbol_id = Column(Integer, ForeignKey("dim_symbol.symbol_id"), primary_key=True, index=True)
    year = Column(Integer, primary_key=True, index=True)
    name = Column(String)
    accounts_payable_current = Column(Numeric)
    accounts_receivable_current = Column(Numeric)
    accumulated_oci_loss_net_of_tax = Column(Numeric)
    assets = Column(Numeric)
    assets_current = Column(Numeric)
    assets_noncurrent = Column(Numeric)
    cash_cash_equivalents_at_carrying_value = Column(Numeric)
    commercial_paper = Column(Numeric)
    commitments_contingencies = Column(String)
    common_stock_shares_issued = Column(Numeric)
    common_stock_shares_outstanding = Column(Numeric)
    common_stocks_additional_paid_in_capital = Column(Numeric)
    contract_customer_liability_current = Column(Numeric)
    inventory = Column(Numeric)
    liabilities = Column(Numeric)
    liabilities_stockholders_equity = Column(Numeric)
    liabilities_current = Column(Numeric)
    liabilities_noncurrent = Column(Numeric)
    long_term_debt_current = Column(Numeric)
    long_term_debt_noncurrent = Column(Numeric)
    marketable_securities_current = Column(Numeric)
    marketable_securities_noncurrent = Column(Numeric)
    nontrade_receivables_current = Column(Numeric)
    other_assets_current = Column(Numeric)
    other_assets_noncurrent = Column(Numeric)
    other_liabilities_current = Column(Numeric)
    other_liabilities_noncurrent = Column(Numeric)
    property_plant_equipment = Column(Numeric)
    retained_earnings_accumulated_deficit = Column(Numeric)
    stockholders_equity = Column(Numeric)
    accounts_payable_accrued_liabilities_current = Column(Numeric)
    accrued_liabilities_current = Column(Numeric)
    additional_paid_in_capital = Column(Numeric)
    common_stock_value = Column(Numeric)
    contract_customer_liability = Column(Numeric)
    deferred_income_tax_assets = Column(Numeric)
    deferred_revenue_current = Column(Numeric)
    funds_held_for_clients = Column(Numeric)
    goodwill = Column(Numeric)
    intangible_assets_excluding_goodwill = Column(Numeric)
    intangible_assets_goodwill = Column(Numeric)
    operating_lease_liability_current = Column(Numeric)
    operating_lease_liability_noncurrent = Column(Numeric)
    operating_lease_right_of_use_asset = Column(Numeric)
    prepaid_expense_other_assets_current = Column(Numeric)
    short_term_investments = Column(Numeric)
    accumulated_oci_available_sale_securities_net_of_tax = Column(Numeric)
    accumulated_oci_pension_postretirement_net_of_tax = Column(Numeric)
    accumulated_oci_foreign_currency_net_of_tax = Column(Numeric)
    aoci_loss_cash_flow_hedge_cumulative_gain_loss_after_tax = Column(Numeric)
    available_for_sale_securities_debt_securities_noncurrent = Column(Numeric)
    deferred_income_tax_liabilities = Column(Numeric)
    employee_related_liabilities_current = Column(Numeric)
    investments = Column(Numeric)
    litigation_reserve_current = Column(Numeric)
    long_term_investments = Column(Numeric)
    accrued_litigation_current = Column(Numeric)
    client_incentives_assets_current = Column(Numeric)
    client_incentives_assets_noncurrent = Column(Numeric)
    client_incentives_liabilities_current = Column(Numeric)
    customer_collateral_assets = Column(Numeric)
    customer_collateral_liabilities = Column(Numeric)
    restricted_cash_cash_equivalents_us_litigation_escrow = Column(Numeric)
    right_to_recover_for_covered_losses = Column(Numeric)
    settlement_payable = Column(Numeric)
    settlement_receivable = Column(Numeric)
    covered_loss_protection_interchange_fees = Column(Numeric)
    accrued_liabilities_current_avg = Column(Numeric)
    common_stock_value_outstanding_avg = Column(Numeric)
    preferred_stock_value_outstanding_avg = Column(Numeric)
    stockholders_equity_noncontrolling_interest_avg = Column(Numeric)
    tsla_digital_assets_non_current = Column(Numeric)
    tsla_accrued_other_current_liabilities = Column(Numeric)
    tsla_long_term_debt_finance_leases_current = Column(Numeric)
    tsla_long_term_debt_finance_leases_noncurrent = Column(Numeric)
    contract_customer_liability_noncurrent = Column(Numeric)
    redeemable_noncontrolling_interest_equity_carrying_amount = Column(Numeric)
    preferred_stock_value = Column(Numeric)
    additional_paid_in_capital_common_stock = Column(Numeric)
    minority_interest = Column(Numeric)
    deferred_costs_leasing_noncurrent_avg = Column(Numeric)
    tsla_leased_assets_avg = Column(Numeric)
    accounts_payable_other_accrued_liabilities_current = Column(Numeric)
    available_for_sale_securities_debt_securities_current = Column(Numeric)
    capitalized_contract_cost_current = Column(Numeric)
    capitalized_contract_cost_noncurrent = Column(Numeric)
    convertible_debt_current = Column(Numeric)
    other_long_term_investments = Column(Numeric)
    net_ppe_finance_lease_assets = Column(Numeric)
    treasury_stock_common_value = Column(Numeric)

    dim_symbol = relationship("DimSymbol", back_populates="balance_sheets")

